application: youtube-playlist-analyzer
version: 1
runtime: php55
api_version: 1
threadsafe: true
automatic_scaling:
  max_instances: 1

handlers:
- url: /
  script: form.php

- url: /submit
  script: playlist_info.php

- url: /c3
  static_dir: c3

error_handlers:
- file: error.html

- error_code: over_quota
  file: overQuota.html
